### ISSUE TITLE
VIN check-digit validation

### ISSUE THREAD

**Issue by elsurudo** [jyunderwood/vin_query#2]
I've already implemented [this algorithm](https://en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/Check_digit) in my rails app as a custom validator, but I think it may make sense to move it into this library instead.

If it were in the library, the client could avoid some needless requests, as it would already know whether a string is a valid VIN or not (whether it's a _real_ VIN is another story, of course).

How do you feel about including this in the gem? I could make a PR at some point.

**Comment by jyunderwood** [comment]
I kind of want to keep this as just a plain API wrapper for vinquery.com.

In the app this was written for, there is a vin service that does the checksum checking and then it either uses VinQuery (and this gem), Chrome Data (if that's the dealership's preference), or a cached profile, if the vehicle has ever been in the system before.

**Comment by elsurudo** [comment]
Fair enough – I thought that might be the case.
